kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'generateirn'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/chaitalittl/TML_eInvoice_GenerateIRN.git'
    sourceSecret:
      name: github-girn  
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev-esb
      jenkinsfilePath: 'Jenkinsfile'